server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      configurations: weighted
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: product-service-1
          uri: http://localhost:19093
          predicates:
            - Path=/products/**
            - Weight=group-product, 7
        - id: product-service-2
          uri: http://localhost:19094
          predicates:
            - Path=/products/**
            - Weight=group-product, 3
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"